<ol class="breadcrumb text-left">
    <?php foreach($this->pages as $page): ?>
        <?php if ($page->isActive()): ?>
            <li class="active"><?=$page->getLabel()?></li>
        <?php else: ?>
            <li><a href="<?=$page->getHref()?>"><?=$page->getLabel()?></a></li>
        <?php endif; ?>
        <?php if ($page->get('identifier')) : ?>
                <?php $identifier = $page->get('identifier'); ?>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($identifier) : ?>
            <li class="active"><span><?=$identifier['identifier']?></span></li>
    <?php endif; ?>
</ol>
