<meta http-equiv="Content-Language" content="en" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description" content="<?=$this->siteInfo->description?>" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

<!-- Bootstrap -->
<link rel="stylesheet" href="/css/bootstrap.3.2.0/css/bootstrap.min.css" />
<link rel="stylesheet" href="/css/bootstrap.3.2.0/css/bootstrap-theme.min.css" />
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
