<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div><h3>Installfest Form Lookup</h3></div>
        </div>
    </div>
<form action="result.php" method="post">
  <label>Name</label>
  <input type="text" name="name">
  <br></br><button type="submit" class="btn btn-primary">Form Lookup </button>
  <a href="/index.php" class="btn btn-primary" role="button">New Submission</a>
</form>

<br>
</div>
