$(document).ready(function(){
    $('input[id="wifi"]').click(function(){
            $("wifi_model").show();
        }
        if($(this).attr("value")=="green"){
            $(".green").toggle();
        }
    });
});
