<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <h3>About Installfest/Linux Workshop</h3>
            Who?
            <br \>
            Anyone interested in learning more about open source or Linux is invited to an open workshop!
            <br \><br \>
            What?:
            <br \>
            We can install most Linux distributions onto almost anything that meets requirements, including Raspberry Pi's and routers. We are also happy to assist with problems, answer questions, or simply discuss free software. We meet every 1st and 3rd Saturday of each month from 10 AM until 4 PM, unless rescheduled otherwise. Please see the calendar at <a href="http://www.azloco.org/?q=node/28"> http://www.azloco.org/?q=node/28</a> or <a href="http://phxlinux.org/">http://phxlinux.org/</a> for more information.
            We provide power and network connectivity as well as install media.
            <br \><br \>
            What to bring?:
            <br \>
            You need to bring everything required to use your computer.
            <br \><br \>
            How can I help?:
            <br \>
            We need volunteers of all skill-sets; you don't have to be a free software veteran to help. If you can manage a linux install, be it Ubuntu on your laptop or Gentoo on a toaster, you can help by submitting a form with the install details. It only takes a few moments, and this information goes directly into a searchable database, providing an invaluable resource of shared experience and knowledge.
        </div>
        <div class="col-xs-12 install-buttons">
          <a href="/default/index/install" class="btn btn-primary" role="button">Installfest Form Submission</a>
          <a href="/default/index/search" class="btn btn-primary" role="button">Form Lookup</a>
        </div>
    </div>
</div>
