<div class="container-fluid">
<form id="install" class="" method="POST" action="/index/install" style="">
    <div class="row">
        <div class="col-sm-6">
            <div><h3>Installation Questionnaire</h3></div>
            <div class="form-group form-group-sm">
                <label class="">Name</label>
                <?=$this->form->name->renderViewHelper()?>
                <?=$this->form->name->renderErrors()?>
            </div>
            <div class="form-group form-group-sm">
                <label class="">Helper Name *</label>
                <?=$this->form->helper_name->renderViewHelper()?>
                <?=$this->form->helper_name->renderErrors()?>
            </div>
            <div class="form-group form-group-sm">
                <label class="">Email</label>
                <?=$this->form->email->renderViewHelper()?>
                <?=$this->form->email->renderErrors()?>
            </div>
            <div class="form-group form-group-sm">
                <label class="">Computer Make *</label>
                <?=$this->form->computer_make->renderViewHelper()?>
                <?=$this->form->computer_make->renderErrors()?>
            </div>
            <div class="form-group form-group-sm">
                <label class="">Computer Model Number *</label>
                <?=$this->form->computer_model_number->renderViewHelper()?>
                <?=$this->form->computer_model_number->renderErrors()?>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="form-group form-group-sm" type="number">
                        <label class="">Memory Amount *</label>
                        <?=$this->form->memory_amount->renderViewHelper()?>
                        <?=$this->form->memory_amount->renderErrors()?>
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="form-group form-group-sm">
                        <label class="">GB/MB</label>
                        <?=$this->form->size_unit->renderViewHelper()?>
                        <?=$this->form->size_unit->renderErrors()?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="form-group form-group-sm" type="number">
                        <label class="">Disk Size *</label>
                            <?=$this->form->disk_size->renderViewHelper()?>
                            <?=$this->form->disk_size->renderErrors()?>
                    </div>
               </div>
               <div class="col-xs-4">
                    <div class="form-group form-group-sm">
                        <label class="">GB/TB</label>
                            <?=$this->form->size_unit_hd->renderViewHelper()?>
                            <?=$this->form->size_unit_hd->renderErrors()?>
                    </div>
              </div>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="form-group form-group-sm" type="number">
                        <label class="">Disk Free Space *</label>
                            <?=$this->form->disk_free_space->renderViewHelper()?>
                            <?=$this->form->disk_free_space->renderErrors()?>
                    </div>
               </div>
                    <div class="col-xs-4">
                        <div class="form-group form-group-sm">
                            <label class="">GB/TB</label>
                                <?=$this->form->size_unit_hd_free->renderViewHelper()?>
                                <?=$this->form->size_unit_hd_free->renderErrors()?>
                        </div>
                    </div>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <div class="form-group form-group-sm">
                        <?=$this->form->backup->renderViewHelper()?>
                        <?=$this->form->backup->renderErrors()?>
                    </div>
                </div>
                <div class="col-xs-8">
                    <div class="form-group form-group-sm">
                        <?=$this->form->disk_cleanup->renderViewHelper()?>
                        <?=$this->form->disk_cleanup->renderErrors()?>
                        <label class="">Disk Cleanup</label>
                    </div>
                    <div class="form-group form-group-sm">
                        <?=$this->form->disk_defrag->renderViewHelper()?>
                        <?=$this->form->disk_defrag->renderErrors()?>
                        <label class="">Disk Defragmented</label>
                    </div>
                </div>
            </div>
            <div class="form-group form-group-sm">
                <label class="">Current Operating System *</label>
                <?=$this->form->old_os->renderViewHelper()?>
                <?=$this->form->old_os->renderErrors()?>
            </div>
            <div class="form-group form-group-sm">
                <label class="">Requested Linux Version</label>
                <?=$this->form->requested_os->renderViewHelper()?>
                <?=$this->form->requested_os->renderErrors()?>
            </div>
            <div class="form-group form-group-sm">
                <?=$this->form->dual_boot->renderViewHelper()?>
                <?=$this->form->dual_boot->renderErrors()?>
            </div>
            <div>* Required Field</div>
        </div>
        <div class="col-sm-6">
            <div><h3>Installation Report</h3></div>
            <!--TODO Javascript to hide/show ethernet and wifi options based on state of checkbox-->
            <div class="form-group form-group-sm">
                <div class="row">
                    <div class="col-xs-2">
                        <div class="form-group form-group-sm">
                            <?=$this->form->wifi->renderViewHelper()?>
                            <?=$this->form->wifi->renderErrors()?>
                            <label class="">Wifi</label>
                        </div>
                    </div>
                    <div class="col-xs-10">
                        <div class="form-group form-group-sm">
                            <label class="">Wifi Model Number</label>
                            <?=$this->form->wifi_model_number->renderViewHelper()?>
                            <?=$this->form->wifi_model_number->renderErrors()?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group form-group-sm">
                <div class="row">
                    <div class="col-xs-2">
                        <div class="form-group form-group-sm">
                            <?=$this->form->ethernet->renderViewHelper()?>
                            <?=$this->form->ethernet->renderErrors()?>
                            <label class="">Ethernet</label>
                        </div>
                    </div>
                    <div class="col-xs-10">
                        <div class="form-group form-group-sm">
                            <label class="">Ethernet Model Number</label>
                            <?=$this->form->ethernet_model_number->renderViewHelper()?>
                            <?=$this->form->ethernet_model_number->renderErrors()?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group form-group-sm">
                <label class="">CPU Model Number *</label>
                <?=$this->form->cpu_model_number->renderViewHelper()?>
                <?=$this->form->cpu_model_number->renderErrors()?>
            </div>
            <div class="form-group form-group-sm">
                <label class="">GPU Model Number *</label>
                <?=$this->form->gpu_model_number->renderViewHelper()?>
                <?=$this->form->gpu_model_number->renderErrors()?>
            </div>
            <div class="form-group form-group-sm">
                <div class="row">
                    <div class="col-xs-6">
                        <label class="">Linux Distro Installed *</label>
                        <?=$this->form->installed_os->renderViewHelper()?>
                        <?=$this->form->installed_os->renderErrors()?>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group form-group-sm">
                            <label class="">Version *</label>
                            <?=$this->form->installed_os_version->renderViewHelper()?>
                            <?=$this->form->installed_os_version->renderErrors()?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group form-group-sm">
              <label class="">Notes</label>
              <?=$this->form->notes->renderViewHelper()?>
              <?=$this->form->notes->renderErrors()?>
            </div>
            <div class="form-group form-group-sm">
                <?=$this->form->lightweight_linux->renderViewHelper()?>
                <?=$this->form->lightweight_linux->renderErrors()?>
                <label class="">Lightweight Linux</label>
            </div>
            <div class="form-group form-group-sm">
                <?=$this->form->updated->renderViewHelper()?>
                <?=$this->form->updated->renderErrors()?>
                <label class="">Updated</label>
            </div>
            <div class="form-group form-group-sm">
                <?=$this->form->resource_list->renderViewHelper()?>
                <?=$this->form->resource_list->renderErrors()?>
                <label class="">Resource List</label>
            </div>
            <div class="form-group form-group-sm">
                <?=$this->form->user_confirmation->renderViewHelper()?>
                <?=$this->form->user_confirmation->renderErrors()?>
                <label class="">User verified</label>
            </div>
        </div>
    </div>
    <button style="display: inline" type="submit" id="install_submit" class="btn btn-primary">Submit</button>
    <a href="/default/index/search" class="btn btn-primary" role="button">Form Lookup</a>
</form>
</div>
